galaxy_info:
  author: dyindude
  description: install or update discord
  role_name: discord
  company: dyindude.net
  issue_tracker_url: "https://github.com/dyindude/ansible-role-discord"
  license: BSD
  min_ansible_version: 2.1.1.0
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
  galaxy_tags:
    - discord
    - debian
    - ubuntu
    - chat
dependencies: []
